// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DecentralizedFinance.Data.Models
{
    public partial class DeFiProject
    {
        public int Id { get; set; }
        public decimal DefiTotalCash { get; set; }
        public decimal TotalValueLocked { get; set; }
        public decimal MakerDominance { get; set; }
        public decimal DeFiPulseIndex { get; set; }
        public DateTime RegisterDate { get; set; }
    }
}