// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DecentralizedFinance.Data.Models
{
    public partial class DeFiProject
    {
        public int Id { get; set; }
        public double? DefiTotalCash { get; set; }
        public double? DefiTvl { get; set; }
    }
}