// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DecentralizedFinance.Data.Models
{
    public partial class Group
    {
        public Group()
        {
            Token = new HashSet<Token>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public double Tvl { get; set; }
        public int Total { get; set; }
        public string PersianName { get; set; }

        public virtual ICollection<Token> Token { get; set; }
    }
}