// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DecentralizedFinance.Data.Models
{
    public partial class Token
    {
        public Token()
        {
            TokenPrice = new HashSet<TokenPrice>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public double? Price { get; set; }
        public string FullName { get; set; }
        public double? TotalAmount { get; set; }
        public string Tvl { get; set; }
        public int? GroupId { get; set; }

        public virtual Group Group { get; set; }
        public virtual ICollection<TokenPrice> TokenPrice { get; set; }
    }
}