// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DecentralizedFinance.Data.Models
{
    public partial class TokenPrice
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public int TokenId { get; set; }
        public double Price { get; set; }

        public virtual Token Token { get; set; }
    }
}